version: '3'
services:
  nginx-proxy:
    container_name: nginx-proxy
    image: 'jc21/nginx-proxy-manager:latest'
    restart: always
    ports:
      - '80:80'
      - '${NGINX_PROXY_MANAGMENT_VIRTUAL_PORT}:81'
      - '443:443'
    volumes:
      - ${NFS_LOCAL_PATH}/nginx-proxy-manager/data:/data
      - ${NFS_LOCAL_PATH}/nginx-proxy-manager/letsencrypt:/etc/letsencrypt
      - ${NFS_LOCAL_PATH}/nginx-proxy-manager/config.json:/app/config/production.json
    networks:
      - nginx-network
networks:
  nginx-network:
    external: true
