version: '3'
volumes:
  portainer_data:
    driver: local
    driver_opts:
      type: nfs
      o: addr=${NFS_MOUNT_ADDRESS},nfsvers=4
      device: :${NFS_PORTAINER_LOCAL_PATH}
services:
  portainer:
    command: -H unix:///var/run/docker.sock
    image: portainer/portainer
    container_name: portainer
    restart: always
    privileged: true
    volumes:
      - portainer_data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - VIRTUAL_HOST=${PORTAINER_VIRTUAL_HOST}
      - VIRTUAL_PORT=${PORTAINER_VIRTUAL_PORT}
    ports:
      - 8000:8000
networks:
  default:
    external:
      name: nginx-network
