version: '3'
services:
  portainer:
    command: -H unix:///var/run/docker.sock
    image: portainer/portainer
    container_name: portainer
    restart: always
    privileged: true
    volumes:
      - /mnt/portainer/data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - VIRTUAL_HOST=${PORTAINER_VIRTUAL_HOST}
      - VIRTUAL_PORT=${PORTAINER_VIRTUAL_PORT}
    ports:
      - 8000:8000
networks:
  default:
    external:
      name: proxy-network
